cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/versions'

brew 'autojump'
brew 'cmake'
brew 'readline'
brew 'bash'
brew 'coreutils'
brew 'gnu-sed'
brew 'pkg-config'
brew 'openssl'
brew 'libevent'
brew 'gettext'
brew 'libpng'
brew 's-lang'
brew 'newt', args: ['with-python']
brew 'tmux'
brew 'findutils'
brew 'gdbm'
brew 'git'
brew 'go'
brew 'gotags'
brew 'httpie'
brew 'icdiff'
brew 'diff-so-fancy'
brew 'leiningen'
brew 'macvim', args: ['with-override-system-vim']
brew 'node'
brew 'tree'
brew 'unrar'
brew 'wget'
brew 'zsh'
brew 'the_silver_searcher'
brew 'homebrew/dupes/grep'
brew 'keybase'

cask 'adobe-reader'
cask 'alfred'
cask 'anki'
cask 'atom'
cask 'dash'
cask 'dropbox'
cask 'evernote'
cask 'google-chrome'
cask 'java'
brew 'gradle'
cask 'iterm2'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'sublime-text3'
cask 'teamviewer'
cask 'the-unarchiver'
cask 'toggldesktop'
cask 'utorrent'
cask 'vlc'
cask 'docker-beta'
