#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source $HOME/.dotfiles/git/githelpers

fpath=(~/.zfunc $fpath)

# autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh  ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# remove dups from history
setopt HIST_IGNORE_DUPS

# without this reattaching to tmux makes the screen unresponsive
# https://gitlab.com/gnachman/iterm2/issues/3995
setopt HUP

# aliases
alias vi="mvim -v -u $HOME/.dotfiles/vim/.vimrc"
alias gometalinter="gometalinter --exclude=\".*should have comment.*\""
